export const GET_PRODUCTS = 'home/GET_PRODUCTS';
export const SET_SEARCHED_PRODUCTS = 'home/SET_SEARCHED_PRODUCTS';
export const SET_BRANDS_FILTER = 'home/SET_BRANDS_FILTER';
export const SET_MODELS_FILTER = 'home/SET_MODELS_FILTER';
export const SET_SORT_FILTER = 'home/SET_SORT_FILTER';
